### ISSUE TITLE
Multi-paragraph endnotes: no line breaks, duplicate links

### ISSUE THREAD

**Issue by pgoussy** [BirkbeckCTP/janeway#2656]
**Describe the bug**
If a footnote/endnote contains multiple `<p>` tags in the JATS, there appear to be two rendering issues in Janeway:

- The separate JATS `<p>`s are combined into a single text block in the HTML, rather than being treated as separate paragraphs
- Within that run-on paragraph, placed at what _would_ be the end of each separate `<p>` from the JATS, Janeway inserts a duplicate caret link ([^]) pointing to the note's callout in the text. This caret link should only appear at the end of the endnote, and there should only be one.

**To Reproduce**
1. Go to https://journals.publishing.umich.edu/ergo/plugins/typesetting/preview_galley/article/1118/galley/417/
2. Click on Notes in the floating TOC
3. Scroll down to note 3 ("It may be helpful to think...")
4. Notice that (a) all of the text runs together in a single block, and (b) there are ten separate [^] links throughout the paragraph. This is obviously an extreme example (most multi-paragraph notes only have two or three paras) but it illustrates the issue very effectively.

Here's how this example is tagged in the JATS:
```
<fn id="FN3">
<label>3</label><p id="P55">It may be helpful to think of <underline>Identity</underline> and <underline>Candidates</underline> as dealing in conditional epistemic probabilities&#x2014;roughly, what one should expect or believe, given one&#x2019;s evidence. This comes to something like the following (for simplicity&#x2019;s sake, we put this in the singular second-person). Where D is the relevant data&#x2014;that is, whatever evidence philosophical theories must take into account&#x2014;and x is a candidate:</p>
<p id="P56"><underline>P-Identity</underline>: If P(x fills the emotional office/D) is high, then either: D is strong evidence that you = x, or you = x</p>
<p id="P57"><underline>P-Candidates:</underline> P(your animal fills the emotional office/D) is high</p>
<p id="P58">Therefore, either D is strong evidence that you = x, or you = x (from P-Identity and P-Candidates, MP)</p>
<p id="P59">The conclusion here is either that animalism is strongly confirmed by the evidence or that animalism is simply true. In either case, the argument supports animalism.</p>
<p id="P60">If you cannot make sense of some candidates being <italic>better</italic> suited for the emotional office than others or of one candidate being the <italic>best</italic>, we offer this alternative formulation of the argument:</p>
<p id="P61"><underline>Identity*</underline>: We are the things that have our emotional states.</p>
<p id="P62"><underline>Candidates*</underline>: The things that have our emotional states are our animals.</p>
<p id="P63">Therefore, we are our animals (from Identity* and Candidates*)</p>
<p id="P64">The conclusion is the same. And nothing we&#x2019;ll say on behalf of our argument will hinge on this difference in formulation.</p>
</fn>
```

**Expected behavior**
Within a footnote/endnote item, each `<p>` in the JATS should render as a separate paragraph in the HTML. However, there should only be one caret [^] linking back up to the note's reference in the text, and that link should appear at the very end of the note. 

**Screenshots**
![2021-12-08_16-47-02](https://user-images.githubusercontent.com/36245100/145289762-49f32a96-f3ee-4428-a3d1-7fb998c5d8c3.png)

**Comment by pgoussy** [comment]
Bumping this up! It appears that the duplicate caret links are no longer showing up, but multi-paragraph footnotes are still displaying with all of the <p> tags merged into a contiguous block of text:
![2023-02-20_17-16-47](https://user-images.githubusercontent.com/36245100/220206252-dd3a5b13-2aaa-46a8-b5ac-838b80a4f6e1.png)

**Comment by pgoussy** [comment]
Bumping this up as we've gotten some author complaints about it, and Apex is claiming that they cannot manually add a line break between these endnote paragraphs. Can this be fixed in the liquid XSLT?

**Comment by pgoussy** [comment]
Bumping this up again, as we've continued to receive author feedback about multiple footnote paragraphs being merged in the HTML version of their articles.

**Comment by ajrbyers** [comment]
@pgoussy can you confirm this issue is still present? When testing with the example you supplied I can see it laid out properly.

![Image](https://github.com/user-attachments/assets/f297dc59-dfd2-4ef2-bfbb-9ef844e3d3f3)

**Comment by pgoussy** [comment]
Hmmm, intriguing! I agree, the original example looks correct now. Maybe it has something to do with the block quote formatting?

Here's the article where the error came up recently--see footnote 10, which should be multiple regular paragraphs:
https://journals.publishing.umich.edu/ergo/article/id/6790/

![image](https://github.com/user-attachments/assets/8a8b44a0-0be5-438a-8cc3-d735de6b0e5c)
